DROP TABLE BANK_ACCOUNTS;

CREATE TABLE BANK_ACCOUNTS (
    ACCOUNT_ID NUMBER PRIMARY KEY,
    ACCOUNT_HOLDER VARCHAR2(50),
    BALANCE NUMBER
);

INSERT INTO BANK_ACCOUNTS VALUES (101,'Allen',10000);
INSERT INTO BANK_ACCOUNTS VALUES (102,'John',20000);
INSERT INTO BANK_ACCOUNTS VALUES (103,'David',15000);
INSERT INTO BANK_ACCOUNTS VALUES (104,'Peter',25000);
COMMIT;

SELECT * FROM BANK_ACCOUNTS;

CREATE OR REPLACE PROCEDURE TransferFunds(
    FROM_ACCOUNT NUMBER,
    TO_ACCOUNT NUMBER,
    AMOUNT NUMBER
)
IS
BEGIN
    UPDATE BANK_ACCOUNTS
    SET BALANCE = BALANCE - AMOUNT
    WHERE ACCOUNT_ID = FROM_ACCOUNT;
    UPDATE BANK_ACCOUNTS
    SET BALANCE = BALANCE + AMOUNT
    WHERE ACCOUNT_ID = TO_ACCOUNT;
    COMMIT;
END;
/

EXEC TransferFunds(101,102,3000);

SELECT * FROM BANK_ACCOUNTS;