DROP TABLE CUSTOMERS;
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50),
    DOB DATE,
    LOAN_INTEREST NUMBER,
    BALANCE NUMBER,
    ISVIP VARCHAR2(5)
);

INSERT INTO CUSTOMERS VALUES(101,'Allen',TO_DATE('15-08-2005','DD-MM-YYYY'),8,5000,'FALSE');
INSERT INTO CUSTOMERS VALUES(102,'John',TO_DATE('20-06-1955','DD-MM-YYYY'),9,15000,'FALSE');
INSERT INTO CUSTOMERS VALUES(103,'David',TO_DATE('11-01-1948','DD-MM-YYYY'),10,20000,'FALSE');
INSERT INTO CUSTOMERS VALUES(104,'Peter',TO_DATE('01-03-1985','DD-MM-YYYY'),8.5,8000,'FALSE');
COMMIT;

SELECT * FROM CUSTOMERS;

SET SERVEROUTPUT ON;
BEGIN
    FOR customer IN (SELECT * FROM CUSTOMERS)
    LOOP
        IF customer.BALANCE > 10000 THEN
            UPDATE CUSTOMERS
            SET ISVIP = 'TRUE'
            WHERE CUSTOMER_ID = customer.CUSTOMER_ID;
            DBMS_OUTPUT.PUT_LINE(customer.CUSTOMER_NAME || ' promoted to VIP.');
        ELSE
            UPDATE CUSTOMERS
            SET ISVIP = 'FALSE'
            WHERE CUSTOMER_ID = customer.CUSTOMER_ID;
            DBMS_OUTPUT.PUT_LINE(customer.CUSTOMER_NAME || ' is not eligible for VIP.');
        END IF;
    END LOOP;
    COMMIT;
END;
/

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    BALANCE,
    ISVIP
FROM CUSTOMERS;