CREATE TABLE ACCOUNTS (
    ACCOUNT_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50),
    BALANCE NUMBER
);
INSERT INTO ACCOUNTS VALUES(1,'Allen',10000);
INSERT INTO ACCOUNTS VALUES(2,'John',20000);
INSERT INTO ACCOUNTS VALUES(3,'David',30000);
INSERT INTO ACCOUNTS VALUES(4,'Peter',40000);
COMMIT;

SELECT * FROM ACCOUNTS;

CREATE OR REPLACE PROCEDURE ProcessMonthlyInterest
IS
BEGIN
    UPDATE ACCOUNTS
    SET BALANCE = BALANCE + (BALANCE * 0.01);
    COMMIT;
END;
/
EXEC ProcessMonthlyInterest;
SELECT * FROM ACCOUNTS;