CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(50),
    SALARY NUMBER,
    PERFORMANCE_RATING CHAR(1)
);
INSERT INTO EMPLOYEES VALUES(101,'Allen',50000,'A');
INSERT INTO EMPLOYEES VALUES(102,'John',45000,'B');
INSERT INTO EMPLOYEES VALUES(103,'David',40000,'C');
INSERT INTO EMPLOYEES VALUES(104,'Peter',55000,'A');
COMMIT;

SELECT * FROM EMPLOYEES;

CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus
IS
BEGIN
    FOR emp IN (SELECT * FROM EMPLOYEES)
    LOOP
        IF emp.PERFORMANCE_RATING = 'A' THEN
            UPDATE EMPLOYEES
            SET SALARY = SALARY + (SALARY * 0.20)
            WHERE EMPLOYEE_ID = emp.EMPLOYEE_ID;
        ELSIF emp.PERFORMANCE_RATING = 'B' THEN
            UPDATE EMPLOYEES
            SET SALARY = SALARY + (SALARY * 0.10)
            WHERE EMPLOYEE_ID = emp.EMPLOYEE_ID;
        ELSE
            UPDATE EMPLOYEES
            SET SALARY = SALARY + (SALARY * 0.05)
            WHERE EMPLOYEE_ID = emp.EMPLOYEE_ID;
        END IF;
    END LOOP;
    COMMIT;
END;
/

EXEC UpdateEmployeeBonus;
SELECT * FROM EMPLOYEES;